# Site settings
title: My Design Portfolio
email: mateusz.wodyk@gmail.com
description: UI/UX specialist and game-fan focused on research of e-commerce and non-commerce webpages/mobile applications and designing prototypes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://example.com" # the base hostname & protocol for your site
twitter_username: mateuszwodyk
github_username: Mat-Teusz
google_username: 114502144040825816739
pinterest_username: mateuszwodyk
linkedin_username: pub/mateusz-wodyk/96/21/780

permalink: /:categories/:title

links:
 - title: about
   url: /about
 - title: work
   url: /work
 - title: articles
   url: /articles
 - title: hire me
   url: /hire-me

# Build settings
markdown: kramdown

